<?php

namespace App\GalleryBundle\Repository;

use Doctrine\ORM\AbstractQuery;
use Doctrine\ORM\EntityRepository;

/**
 * AlbumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlbumRepository extends EntityRepository
{
    public function getAlbumsToView()
    {
        return $this->createQueryBuilder('a')
            ->select('a.id, a.name, a.description')
            ->getQuery()
            ->getResult(AbstractQuery::HYDRATE_ARRAY);
    }

    public function getAlbumWithImages()
    {
        return $this->createQueryBuilder('a')
            ->leftJoin('a.images', 'i')
            ->getQuery()
            ->getResult();
    }
}
