<?php

namespace App\GalleryBundle\Repository;

use Doctrine\ORM\AbstractQuery;
use Doctrine\ORM\EntityRepository;

/**
 * AlbumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlbumRepository extends EntityRepository
{
    public function getAlbumsAsArray()
    {
        return $this->createQueryBuilder('a')
            ->select('a.id, a.name, a.description')
            ->getQuery()
            ->getResult(AbstractQuery::HYDRATE_ARRAY);
    }

    public function getAlbumById($albumId)
    {
        return $this->createQueryBuilder('a')
            ->where('a.id = :id')
            ->setParameter('id', $albumId)
            ->getQuery()
            ->getResult();
    }
}
