parameters:
    app_gallery.view_data_manager.class: App\GalleryBundle\Manager\ViewDataManager

services:
    app_gallery.view_data_manager:
        class: %app_gallery.view_data_manager.class%
        arguments: ['@doctrine', '@knp_paginator']
